base_url = "https://grahamenos.com"
author = "Graham Enos"
title = "Graham Enos"
description = "math, programming, statistics, and data"
compile_sass = false
build_search_index = false
minify_html = true
generate_feeds = true

[markdown]
bottom_footnotes = true
smart_punctuation = true

[markdown.highlighting]
error_on_missing_language = true
theme = "github-light"

[extra]
